### ISSUE TITLE
Missing Meta File Error

### ISSUE THREAD

**Issue by scydetracked** [getbraincloud/braincloud-unity-package#2]
When importing BrainCloud as a UPM package, there is a missing meta file error;
`Asset Packages/com.bitheads.braincloud/Runtime/Items has no meta file, but it's in an immutable folder. The asset will be ignored.`

The missing meta seems to be for the 'Items' folder which only contains a meta file for a missing folder called 'Debug'

Either a meta file needs to be created for the 'Items' folder or the 'Debug.meta' file should be removed to prevent the creation of the 'Items' folder

**Comment by francobithead** [comment]
This has been resolved as of version 4.15
