### ISSUE TITLE
bug: Pkg Excludes BrainCloudWrapper

### ISSUE THREAD

**Issue by dylanh724** [getbraincloud/braincloud-unity-package#9]
BrainCloudWrapper is excluded from this pkg - I couldn't see any notes that this would be intentional. Noticed when I was trying to swap BC asset with the pkg in v5.

**Comment by michaelc-bitheads** [comment]
Hello!

Hmm, `BrainCloudWrapper` should always be included in the C# client. It is currently located [here](https://github.com/getbraincloud/braincloud-unity-package/blob/master/Runtime/Client/BrainCloud/BrainCloudWrapper.cs).

There was a very brief period during the 5.0.0 release when Jenkins didn't configure the file structure properly but it was quickly fixed. If you managed to pull from the GitHub during this period then you should definitely be able to update now. If Unity's still having trouble finding it on your end, maybe try removing the plugin and deleting your Library folder before adding it back in?

Let us know if this has been resolved or not!

Thanks,
-Michael Costa
